<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" Version="22.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Focus.Core\Focus.Core.csproj" />
  </ItemGroup>

</Project>
